Remove test summary from test output.
flackr/scroll-timeline pull request #211
Opened 2024-01-25 21:18 UTC by flackr

Having the summary line leads to every PR which alters test expectations conflicting with every other PR which alters them. The summary can be computed by grepping the PASS / FAIL lines anyways so this should reduce the number of merge conflicts to only cases where the same sets of test expectations changed.

2024-01-25 21:31 UTC, flackr commented
@johannesodland I'm hoping this helps reduce the churn with multiple PRs

2024-01-26 08:16 UTC, johannesodland commented
Maybe we could add the summary line to the workflow summary?

```
      - name: Adding summary
        run: echo "Passed $(grep -c '^PASS' ./test/report/summary.txt) of $(grep -c '^'  ./test/report/summary.txt) tests" >> $GITHUB_STEP_SUMMARY
```

2024-01-26 08:36 UTC, bramus commented
Good call. It’s something that was causing some friction indeed.

I like Johannes’s suggestion to add an informative line to the build pipeline’s output.

2024-01-26 13:52 UTC, bramus requested changes
Good call. It’s something that was causing some friction indeed.

I like Johannes’s suggestion to add an informative line to the build pipeline’s output.

2024-01-29 14:57 UTC, flackr commented
> Maybe we could add the summary line to the workflow summary?
> 
> ```
>       - name: Adding summary
>         run: echo "Passed $(grep -c '^PASS' ./test/report/summary.txt) of $(grep -c '^'  ./test/report/summary.txt) tests" >> $GITHUB_STEP_SUMMARY
> ```

Great suggestion, I've added this step as suggested.

2024-01-29 15:23 UTC, bramus commented on .github/workflows/gh-pages.yml
> +      - name: Adding summary
Suggestion to reword the step name, as it doesn’t really “add” anything.

```suggestion
      - name: Test Results
```

2024-01-29 15:27 UTC, bramus approved these changes

2024-01-29 15:49 UTC, merged