Return "normal" for get rangeStart and rangeEnd
flackr/scroll-timeline pull request #223
Opened 2024-02-03 16:37 UTC by johannesodland

We should return the string "normal" for rangeStart and rangeEnd, and not the a TimelineRangeOffset. 

This change makes `view-timeline-get-set-range.html` pass again, given that it is run on an uncompressed build (https://github.com/flackr/scroll-timeline/pull/200)  and that we have a proper implementation of CSSNumericValue.parse() (https://github.com/flackr/scroll-timeline/pull/206).

2024-02-03 19:32 UTC, bramus approved these changes

2024-02-04 07:12 UTC, bramus commented
#206 and #225 are in, so the test results can get updated as part of this PR.

2024-02-04 07:13 UTC, bramus requested changes
https://github.com/flackr/scroll-timeline/pull/206 and https://github.com/flackr/scroll-timeline/pull/225 are in, so the test results can get updated as part of this PR.

2024-02-04 10:16 UTC, johannesodland commented
@bramus Thanks for letting me know 🙏

I've rebased the branch, and the tests are now passing :)

2024-02-06 16:45 UTC, flackr approved these changes

2024-02-06 17:32 UTC, merged